'Y', 'Z'] for i in range(len(info_list)): s = 0 c = 0 l = 0 L = len(info_list[i][1])
if L>=8: l +=1 for sl in small_letters : if sl in info_list[i][1]: s +=1 for cl in capital_letters: if cl in info_list[i][1]: c +=1 if l>0 and s>0 and c>0: return info_list[i][0]

file_text = open("C:\Users\TOSHIBA\Desktop\Decoding The Puzzle\mysterious.txt","r") rd_file = file_text.read() x = decrypt_clue(rd_file)

file = open("C:\Users\TOSHIBA\Desktop\Decoding The Puzzle\puzzles.txt","r+") rd_file = file.readlines() line = [line.rstrip('\n') for line in rd_file] solved_puzzle = solve_puzzles(line)

start = 0 end = 16 magic_nums = calculate_magic_numbers(start,end) test_num = exam_numbers(magic_nums)

employee_info = [("@ahmad","12345Sav#@"),("#ali","234t")] userName = check_pass(employee_info) if userName: print(f"{userName} has the strongest password!") else: print("No one has striong password!")

unlock_vault(x,solved_puzzle,magic_nums,test_num, userName)

def draw_word():

s = turtle.Screen()
s.title("MAGIC")
s.bgcolor("black")
turtle.shape("turtle")
turtle.speed("slow")
turtle.pensize(4)
turtle.pencolor("green")
turtle.fillcolor("green")
turtle.ht()

turtle.penup()
turtle.goto(140,50)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.right(30)
turtle.forward(30)
turtle.left(120)
turtle.forward(30)
turtle.left(125)
turtle.forward(100)
    
turtle.penup()
turtle.goto(80,0)
turtle.pendown()
turtle.circle(-5,360)
turtle.penup()
turtle.goto(60,0)
turtle.pendown()
turtle.circle(-5,360)
turtle.penup()
turtle.goto(100,-20)
turtle.pendown()
turtle.left(150)
turtle.forward(10)
turtle.right(90)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
    
turtle.penup()
turtle.goto(-30,-20)
turtle.pendown()
turtle.right(180)
turtle.forward(30)
turtle.right(90)
turtle.forward(50)
turtle.right(140)
turtle.forward(100)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.goto(-10,-60)
turtle.pendown()
turtle.circle(-5,360)
turtle.done() draw_word()